### ISSUE TITLE
Update all out of date NuGet packages and encapsulate dependencies

### ISSUE THREAD

**Issue by SeanFarrow** [nullean/proc#3]
Given that this package uses prerelease packages, would it be worth updating these to released versions?

Also, should this package encapsulate system.Reactive.* packages, just like things such as ElasticSearch does with Json.net?

**Comment by Mpdreamz** [comment]
It should yeah, something is currrently not right with the build not sure what broke the encapsulation.

Also need to investigate bumping the version and their implications

**Comment by Mpdreamz** [comment]
This commit : https://github.com/nullean/proc/commit/3d1867ada709142202d028932705580b74cafb63

Fixes the rewrite for netstandard2.0 and net45 TFM's now released in `0.4.3`

**Comment by SeanFarrow** [comment]
OK, feel free to close.b
